/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oca.project;

import java.util.ArrayList;

/**
 *
 * @author 90048753
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    
    ArrayList<Person> personList2;
    private static ArrayList<String> bonusAssignedList = new ArrayList<String>();
    private static ArrayList<PayrollReportItem> fortnightPayments = new ArrayList<PayrollReportItem>();
    private static ArrayList<PayrollReportItem> monthlyPayments = new ArrayList<PayrollReportItem>();
  
    
    public MainForm() {
        initComponents();
    }
    
    public static void addBonusEntry (String bonus){
       bonusAssignedList.add(bonus);
    }
    
    public static ArrayList<String> getBonusEntries(){
        return bonusAssignedList;
    }
    
    public static void addFortnightPayment (PayrollReportItem payrollReportItem){
       fortnightPayments.add(payrollReportItem);
    }
    
    public static ArrayList<PayrollReportItem> getFortnightPayments(){
        return fortnightPayments;
    }
    
     public static void addMonthlyPayment (PayrollReportItem payrollReportItem){
       monthlyPayments.add(payrollReportItem);
    }
    
    public static ArrayList<PayrollReportItem> getMonthlyPayments(){
        return monthlyPayments;
    }

// this method gets the list of person created in the main method and sets it in personList2       
    public void setList(ArrayList<Person> inputlist){
        this.personList2 = inputlist;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAssignBonusForm = new javax.swing.JButton();
        btnPerDetConDataForm = new javax.swing.JButton();
        btnRunReports = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Best IT Payroll");

        btnAssignBonusForm.setText("Assign Bonus");
        btnAssignBonusForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignBonusFormActionPerformed(evt);
            }
        });

        btnPerDetConDataForm.setText("Personal Detail and Contractor Data Entry");
        btnPerDetConDataForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerDetConDataFormActionPerformed(evt);
            }
        });

        btnRunReports.setText("Run Reports");
        btnRunReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunReportsActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRunReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAssignBonusForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPerDetConDataForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnClose)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(btnAssignBonusForm, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPerDetConDataForm, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRunReports, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignBonusFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignBonusFormActionPerformed
        AssignBonusForm assignBonusForm = new AssignBonusForm();
        assignBonusForm.setVisible(true);
        assignBonusForm.setList(personList2);
        assignBonusForm.populateManagerComboBox();
    }//GEN-LAST:event_btnAssignBonusFormActionPerformed

    private void btnPerDetConDataFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerDetConDataFormActionPerformed
        PerDetContDataEntryForm perDetContDataEntryForm = new PerDetContDataEntryForm();
        perDetContDataEntryForm.setVisible(true);
        perDetContDataEntryForm.setList(personList2);
        perDetContDataEntryForm.populateNameComboBox();
    }//GEN-LAST:event_btnPerDetConDataFormActionPerformed

    private void btnRunReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunReportsActionPerformed
        PayrollReportsForm payrollReportsForm = new PayrollReportsForm();
        payrollReportsForm.setVisible(true);
        payrollReportsForm.setList(personList2);
        payrollReportsForm.populateNameComboBox();
    }//GEN-LAST:event_btnRunReportsActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignBonusForm;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnPerDetConDataForm;
    private javax.swing.JButton btnRunReports;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
